# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cin', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('date_embauche', models.DateField()),
                ('type_contrat', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=50)),
                ('enfant', models.IntegerField()),
                ('pole', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
