# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_dateactivite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
