# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dateactivite',
            name='synthese',
        ),
        migrations.RemoveField(
            model_name='synthese',
            name='raison',
        ),
        migrations.DeleteModel(
            name='conge',
        ),
        migrations.DeleteModel(
            name='dateactivite',
        ),
        migrations.DeleteModel(
            name='raison',
        ),
        migrations.DeleteModel(
            name='synthese',
        ),
    ]
