# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_raison'),
    ]

    operations = [
        migrations.CreateModel(
            name='dateactivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.TimeField()),
                ('pause', models.TimeField()),
                ('sortie', models.TimeField()),
                ('date_debut', models.DateField()),
                ('nbr_jour', models.PositiveIntegerField()),
            ],
        ),
    ]
