# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_dateactivite'),
    ]

    operations = [
        migrations.CreateModel(
            name='synthese',
            fields=[
                ('jour', models.DateField(primary_key=True, serialize=False)),
                ('dateactivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.dateactivite', unique=True)),
                ('raison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.raison', unique=True)),
            ],
        ),
    ]
