# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20160804_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conge',
            old_name='datedebut_conge',
            new_name='datedebutconge',
        ),
    ]
