# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0015_auto_20160804_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='typedocument',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='synthese',
            name='dateactivite',
        ),
        migrations.RemoveField(
            model_name='synthese',
            name='raison',
        ),
        migrations.RemoveField(
            model_name='conge',
            name='user',
        ),
        migrations.AddField(
            model_name='conge',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='dateactivite',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.DeleteModel(
            name='raison',
        ),
        migrations.DeleteModel(
            name='synthese',
        ),
        migrations.DeleteModel(
            name='typedocument',
        ),
    ]
