# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_auto_20160805_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='typedocument',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='synthese',
            name='dateactivite',
        ),
        migrations.RemoveField(
            model_name='synthese',
            name='raison',
        ),
        migrations.DeleteModel(
            name='Conge',
        ),
        migrations.DeleteModel(
            name='dateactivite',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.DeleteModel(
            name='raison',
        ),
        migrations.DeleteModel(
            name='synthese',
        ),
        migrations.DeleteModel(
            name='typedocument',
        ),
    ]
