# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0021_auto_20160805_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typedocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.typedocument'),
        ),
    ]
