# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0023_auto_20160805_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_demande', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='synthese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('entree', models.TimeField()),
                ('pause', models.TimeField()),
                ('sortie', models.TimeField()),
                ('date_debut', models.DateField(null=True)),
                ('nbr_jour', models.PositiveIntegerField(null=True)),
                ('raison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.raison')),
            ],
        ),
        migrations.CreateModel(
            name='typedocument',
            fields=[
                ('id_type', models.IntegerField(primary_key=True, serialize=False)),
                ('types', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='typedocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.typedocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
