# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0024_auto_20160805_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthese',
            name='raison',
        ),
        migrations.DeleteModel(
            name='synthese',
        ),
    ]
