# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0025_auto_20160805_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonactivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(null=True)),
                ('nbr_jour', models.PositiveIntegerField(null=True)),
                ('raison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.raison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='synthese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('entree', models.TimeField()),
                ('pause', models.TimeField()),
                ('sortie', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
