# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0036_auto_20160809_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='typedocument',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AlterField(
            model_name='nonactivite',
            name='raison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Raison'),
        ),
        migrations.DeleteModel(
            name='document',
        ),
    ]
