# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0045_auto_20160815_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('date_embauche', models.DateField()),
                ('enfant', models.IntegerField()),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Contrat')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='typedocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Typedocument'),
        ),
        migrations.AlterField(
            model_name='nonactivite',
            name='raison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Raison'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='souspole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Souspole'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Pole'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Situation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
