# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0049_auto_20160816_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedemande', models.DateTimeField(auto_now_add=True)),
                ('valide', models.PositiveIntegerField(default=0)),
                ('typedocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Typedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='nonactivite',
            name='raison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Raison'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='souspole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Souspole'),
        ),
    ]
