# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0059_auto_20160902_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='typedocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Typedocument'),
        ),
        migrations.AlterField(
            model_name='nonactivite',
            name='raison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Raison'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='souspole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Souspole'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Document', unique=True),
        ),
    ]
